fluidPage(titlePanel("Heartworm stuff"),
          fluidRow(
            column(6,
                   wellPanel(h3(textOutput("selecteddatemap"),
                             br(),
                             dateInput("dates", label=NULL, value = (Sys.Date()-2), min = min(dseq), max = max(dseq)),
                             plotOutput("binaryoutput", height=700, width=850))),
                   br(),
                   br(),
                   br(),
                   br()),
            column(6,
                   wellPanel(h4(strong('What is happening in the capital cities?')),
                             tableOutput("capital.cities"))),
            column(6,
                   wellPanel(radioButtons(inputId = "summaryselection", 
                                          label=h4(strong("10 year summary of transmission zones")),
                                          #choices=c("1970-1979", "1980-1989", "1990-1999", "2000-2009", "2010-2019"),
                                          choiceNames = c("1970-1979", "1980-1989", "1990-1999", "2000-2009", "2010-2019", "summary GIF", "51-year summary"),
                                          choiceValues = c("1.7079sum.png", "2.8089sum.png", "3.9099sum.png", "4.0009sum.png", "5.1019sum.png", "summary.gif", "51yearsumm.png"),
                                          selected=NULL),
                             imageOutput("summaryImage")),
                   br(),
                   br(),
                   br(),
                   br(),
                   br(),
                   br(),
                   br(),
                   br())
          ),
          br(),
          br(),
          br(),
          br(),
          br(),
          br(),
          fluidRow(
            column(12,
                   br(),
                   br(),
                   br(),
                   br(),
                   wellPanel((h3("Location")),
                             # br(),
                             textInput("postcode", "Enter your postcode:"),
                             textOutput("postcode"),),
                   plotOutput("locationplot")
                   )
            ),
          fluidRow(
           column(6,
                  wellPanel(p(strong(paste(as.Date((Sys.Date()-2), format = "%d-%m-%Y"), "'s", " status:", sep="")),
                              textOutput(("dailystatus")))),
                  wellPanel(dataTableOutput("cutofftable"))
            ),
           column(6,
                  wellPanel(dataTableOutput("percentagetable")))
          )
)

